export const FAIL_RESPONSABLE = "FAIL_RESPONSABLE";
export const GET_RESPONSABLE = "GET_RESPONSABLE";
export const GET_RESPONSABLES = "GET_RESPONSABLES";
export const LOAD_RESPONSABLE = "LOAD_RESPONSABLE";
export const LOGIN_RESPONSABLE = "LOGIN_RESPONSABLE";
export const REGISTER_RESPONSABLE = "REGISTER_RESPONSABLE";
export const CURRENT_RESPONSABLE = "CURRENT_RESPONSABLE";
export const LOGOUT_RESPONSABLE = "LOGOUT_RESPONSABLE";
